namespace FromTheForge.Model;

public static class Constants
{
	public static string Register = "/api/auth/register";
	public static string Login = "/api/auth/login";
	public static string Me = "/api/auth/me";
	public static string CreateCharacter = "/api/characters";
	public static string Allocate = "api/characters/allocate-stat";
	public static string GetCharacter = "/api/characters/me";
	public static string Travel = "/api/travel/move";
	public static string Go = "/api/travel/go";
	public static string TravelStatus = "/api/travel/status";
	public static string TravelCancel = "/api/travel/cancel";
	public static string Map = "/api/map";
	public static string Regions = "/api/map/regions";
	public static string MapDetail = "/api/map/cell";
	public static string CombatStatus = "/api/combat/status";
	public static string CombatAction = "/api/combat/action";
	public static string Inventory = "/api/inventory";
	public static string Pickup = "/api/inventory/pick-up";
	public static string Drop = "/api/inventory/drop";
	public static string Equip = "/api/inventory/equip";
	public static string Unequip = "/api/inventory/unequip";
	public static string Use = "/api/inventory/use";
	public static string Spells = "/api/spells";
	public static string SpellsLearn = "/api/spells/learn";
	public static string SpellsCast = "/api/spells/cast";
	public static string RestCamp = "/api/rest/camp";
	public static string RestInn = "/api/rest/inn";
	public static string RestStatusPath = "/api/rest/status";
	public static string RestStop = "/api/rest/stop";
	public static string Shops = "/api/shops";
	public static string QuestAvailable = "/api/quests/available";
	public static string QuestActive = "/api/quests/active";
	public static string QuestAccept = "/api/quests/accept";
	public static string QuestTurnIn = "/api/quests/turn-in";
	public static string QuestAbandon = "/api/quests/abandon";
	public static string DungeonStatusPath = "/api/dungeons/status";
	public static string DungeonEnter = "/api/dungeons/enter";
	public static string DungeonAdvance = "/api/dungeons/advance";
	public static string DungeonLeave = "/api/dungeons/leave";
	public static string GatheringSkills = "/api/gathering/skills";
	public static string GatheringNodes = "/api/gathering/nodes";
	public static string GatheringHarvest = "/api/gathering/harvest";
	public static string CraftingSkills = "/api/crafting/skills";
	public static string CraftingRecipes = "/api/crafting/recipes";
	public static string CraftingStations = "/api/crafting/stations";
	public static string CraftingCraft = "/api/crafting/craft";
	public static string GameRaces = "/api/game/races";
	public static string GameClasses = "/api/game/classes";
	public static string GameItems = "/api/game/items";
	public static string GameSpells = "/api/game/spells";
}
